env: "" # This should be overridden by environment-specific value files
bootstrap:
  source:
    repoURL: https://github.com/alex-kumpula/ArgoCD-Test-3
    path: bootstrap
root:
  source:
    repoURL: https://github.com/alex-kumpula/ArgoCD-Test-3
    path: root
appCommonSettings: 
  spec:
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
apps:
  nginx:
    enabled: false
    namespace: default
    source:
      chart: nginx
      repoURL: registry-1.docker.io/bitnamicharts
      targetRevision: 15.9.0



